regions = [
    {'id': 0, 'option': 'Total Nacional', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': 1, 'option': 'Alto Patía - Norte del Cauca', 'img': '<img src="https://colaboracion.dnp.gov.co/CDT/PublishingImages/Pactos%20Territoriales/Contrato%20Plan%20Cauca.png" alt="imagen Norte del cauca">'},
    {'id': 2, 'option': 'Arauca', 'img': '<img src="https://comisiondelaverdad.co/especiales/verdadconsentido/img/mapa_arauca.png" alt="imagen colombia">'},
    {'id': 3, 'option': 'Bajo Cauca y Nordeste Antioqueño', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': 4, 'option': 'Catatumbo', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': 5, 'option': 'Chocó', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': 6, 'option': 'Cuenca del Caguán y Piedemonte Caqueteño', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': 7, 'option': 'Macarena - Guaviare', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': 8, 'option': 'Montes de María', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': 9, 'option': 'Pacífico Medio', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': 10, 'option': 'Pacífico y Frontera Nariñense', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': 11, 'option': 'Putumayo', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': 12, 'option': 'Sierra Nevada -Perijá', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': 13, 'option': 'Sur de Bolívar', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': 14, 'option': 'Sur de Córdoba', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': 15, 'option': 'Sur del Tolima', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': 16, 'option': 'Urabá Antioqueño', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'}
]

departments = [
    {'id': '0', 'option': 'Total Nacional', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': '1', 'option': 'AMAZONAS', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png'},
    {'id': '2', 'option': 'ANTIOQUIA', 'img': '<img src="https://comisiondelaverdad.co/especiales/verdadconsentido/img/mapa_arauca.png" alt="imagen colombia">'},
    {'id': '3', 'option': 'ARAUCA', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': '4', 'option': 'ARCHIPIELAGO SAN ANDRES PSC', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': '5', 'option': 'ATLANTICO', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': '6', 'option': 'BOGOTA, D.C', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': '7', 'option': 'BOLIVAR', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': '8', 'option': 'BOYACA', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': '9', 'option': 'CALDAS', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': '10', 'option': 'CAQUETA', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': '11', 'option': 'CASANARE', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': '12', 'option': 'CAUCA', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': '13', 'option': 'CESAR', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': '14', 'option': 'CHOCO', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': '15', 'option': 'CORDOBA', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': '16', 'option': 'CUNDINAMARCA', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': '17', 'option': 'GUAINIA', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': '18', 'option': 'GUAVIARE', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': '19', 'option': 'HUILA', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': '20', 'option': 'LA GUAJIRA', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': '21', 'option': 'MAGDALENA', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': '22', 'option': 'META', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': '23', 'option': 'NARIÑO', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': '24', 'option': 'NORTE DE SANTANDER', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': '25', 'option': 'PUTUMAYO', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': '26', 'option': 'QUINDIO', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': '27', 'option': 'RISARALDA', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': '28', 'option': 'SANTANDER', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': '29', 'option': 'SUCRE', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': '30', 'option': 'TOLIMA', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': '31', 'option': 'VALLE DEL CAUCA', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': '32', 'option': 'VAUPES', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
    {'id': '33', 'option': 'VICHADA', 'img': '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/135px-Flag_of_Colombia.svg.png" alt="imagen colombia">'},
]
